### ISSUE TITLE
Can StdOut be captured from multiple commands concurrently?

### ISSUE THREAD

**Issue by leonj1** [cirocosta/cr#11]
I'm trying to figure out how to capture the output from GetReleaseTag and GetBuildVersion to be used in other tasks. From the docs, it seems captured output will only go to one variable called .Output but unclear how to use it.

```
Jobs:
  - Id: 'GetReleaseTag'
    Run: 'python get_latest_git_release_tag.py'
    CaptureOutput: true

  - Id: 'GetBuildVersion'
    Run: 'python get_docker_build_version.py'
    CaptureOutput: true

  - Id: 'Echo'
    Run: 'echo ${FOO}'
    DependsOn: [ 'GetImageTag' ]
    Env:
      RELEASE_TAG: '.Output'
```

**Comment by cirocosta** [comment]
Hey @leonj1, sorry if the docs are a bit misleading, I’ll make sure I update them soon!

To make use of the output of an execution you must reference the job explicitly, like ‘.Jobs.GetReleaseTag.Output’ and ‘.Jobs.GetBuildVersiob.Output’. This way, whenever it comes the time to execute ‘Echo’, the job output can be properly retrieved.

By the way, if ‘Echo’ needs the output of ‘GetBuildVersion’, then it needs to declare it as a dependency (‘cr’ doesn’t implicitly makes it a dependency right now).

Please let me know if this helps! I’m writing from my celphone right now so maybe there’s something wrong in the response.

Have a good one!

**Comment by cirocosta** [comment]
Oh, and don’t forget ‘{{ }}’, otherwise it won’t be replaced 👍

**Comment by leonj1** [comment]
Awesome! This works
```
Jobs:
  - Id: 'GetReleaseTag'
    Run: 'python get_latest_git_release_tag.py'
    CaptureOutput: true

  - Id: 'GetImageTag'
    Run: 'python get_docker_build_version.py'
    CaptureOutput: true

  - Id: 'Echo'
    Run: 'echo {{ .Jobs.GetImageTag.Output }}'
    DependsOn: [ 'GetImageTag' ]
```
