### ISSUE TITLE
Merge global and job-specific environment with current environment

### ISSUE THREAD

**Issue by cirocosta** [cirocosta/cr#3]
Hey,

right now we allow the specification of a global environment (`.Config.Env`) as well as job-specific environment (`.Jobs.MyJob.Env`) but we're not making use of the result of the merge of these environment when performing the execution.

As I see, the best case would be to perform the merge of these environments at job execution time overriding the`.Jobs.MyJob.Env` with the result such that other jobs could refer to them in their templates if desired.

For instance:

```yaml
Env:
  CAZ: 'BAZ'

Jobs:
  - Id: 'Job1'
    Env:
      FOO: 'BAR'

Jobs:
  - Id: 'Job2'
    Run: 'echo job1env={{ .Jobs.Env.FOO }} ; env'
    DependsOn: [ 'Job1' ]
```

would lead to:

```
BAR
CAZ=BAZ
```
