### ISSUE TITLE
Support for read / prompt / dialogue input

### ISSUE THREAD

**Issue by reggi** [cirocosta/cr#5]
I have a simple example below, where I'd want user input then continue the next script that uses the variable set from `read`.

```
Jobs:
  - Id: 'setExample'
    Run: 'echo "Give me an example:" && read EXAMPLE && export EXAMPLE'
  - Id: 'echoExample'
    Run: 'echo $EXAMPLE'
    DependsOn: [ 'setExample' ]
```
