### ISSUE TITLE
Env vars do not work as expected

### ISSUE THREAD

**Issue by reggi** [cirocosta/cr#6]
In the following I would expect `example` to be returned to stdout. I am seeing an empty space:

```
Env:
  EXAMPLE: 'example'
Jobs:
  - Id: 'echo'
    Run: 'echo $EXAMPLE'
```

```
➜  xxx git:(master) ✗ ../cr --file ./cr-example.yaml --stdout

        Starting execution.

        Logs directory: /tmp

echo    status=STARTED  start=13:29:34

echo    status=SUCCESS  start=13:29:34  elapsed=6.259403ms
```
