### ISSUE TITLE
Runtime stdout does not work

### ISSUE THREAD

**Issue by reggi** [cirocosta/cr#7]
Given this file:

```
Runtime:
  Stdout: true
Jobs:
  - Id: 'echo'
    Run: 'echo "hello"'
```

When I pass in `--stdout`.

```
➜  xxx git:(master) ✗ ../cr --file ./cr-example.yaml --stdout

        Starting execution.

        Logs directory: /tmp

echo    status=STARTED  start=13:30:25
hello
echo    status=SUCCESS  start=13:30:25  elapsed=6.562044ms
```

Without the flag, nothing:

```
➜  xxx git:(master) ✗ ../cr --file ./cr-example.yaml

        Starting execution.

        Logs directory: /tmp

echo    status=STARTED  start=13:30:28
echo    status=SUCCESS  start=13:30:28  elapsed=5.872205ms
```
