### ISSUE TITLE
Make use of configurable global `Directory` variable

### ISSUE THREAD

**Issue by cirocosta** [cirocosta/cr#8]
Hey,

right now we advertise the possibility of setting `Directory` as the default directory to be used as `cwd` but we're not actually using it at the directory resolution method.

Assuming that we have a `cr` file as follows:

```yaml
---
Runtime:
  Directory: '/var/run/cr'
Jobs:
  - Id: 'Job1'
    Run: 'echo Job1_pwd=$(pwd)'

  - Id: 'Job2'
    Directory: '/tmp'
    Run: 'echo Job2_pwd=$(pwd)'
```

The result from the execution would be something like:

```
Job1_pwd=/var/run/cr
Job2_pwd=/tmp
```
